Feat/lecture
edoreld/Dauphine-Data pull request #14
Opened 2019-02-22 15:35 UTC by amramo17

Bonjour Monsieur,
Comme discuté pendant la réunion avec vous dans le cours de vendredi 22 février,
Ma classe a été merger par erreur et l'annulation du merge aura un impacte sur le travail des autres membres ce qui nous a empêché d'annuler le merge.
je vous remercie pour votre compréhension, et de bien vouloir regarder mes modifications.
Merci.

2019-02-22 15:36 UTC, amramo17 commented
la suite de la PR #9

2019-02-24 16:14 UTC, oliviercailloux requested changes
Avez-vous testé le code ?

2019-02-24 16:14 UTC, oliviercailloux commented on dauphine-open-data-lib/src/main/java/io/github/oliviercailloux/y2018/opendata/entity/Lecture.java
> +	private Date date;
Non, utiliser Instant. Voir tutoriel Oracle date/time.

2019-02-24 16:14 UTC, oliviercailloux commented on dauphine-open-data-lib/src/main/java/io/github/oliviercailloux/y2018/opendata/entity/Lecture.java
>  	 */
Ce commentaire est utile et doit être visible des utilisateurs de la classe.

2019-02-24 16:14 UTC, oliviercailloux commented on dauphine-open-data-lib/src/main/java/io/github/oliviercailloux/y2018/opendata/entity/Lecture.java
>  	 */
Commentaire inutile, par contre, il serait bien de préciser l’unité de mesure.

2019-02-24 16:14 UTC, oliviercailloux commented on dauphine-open-data-lib/src/main/java/io/github/oliviercailloux/y2018/opendata/entity/Lecture.java
>  	 */
Vous tentez une communication avec des extra-terrestres ?

2019-02-25 20:25 UTC, amramo17 commented on dauphine-open-data-lib/src/main/java/io/github/oliviercailloux/y2018/opendata/entity/Lecture.java
> +	private Date date;
@oliviercailloux 
Corrigé en remplaçant le type date par Instant.

2019-02-25 20:29 UTC, amramo17 commented on dauphine-open-data-lib/src/main/java/io/github/oliviercailloux/y2018/opendata/entity/Lecture.java
>  	 */
@oliviercailloux 
Corrigé en explicitant l'unité.

2019-02-25 20:30 UTC, amramo17 commented on dauphine-open-data-lib/src/main/java/io/github/oliviercailloux/y2018/opendata/entity/Lecture.java
>  	 */
@oliviercailloux
Corrigé en explicitant l'unité

2019-02-25 20:31 UTC, amramo17 commented on dauphine-open-data-lib/src/main/java/io/github/oliviercailloux/y2018/opendata/entity/Lecture.java
>  	 */
@oliviercailloux 
Corrigé Monsieur. Je vous remercie pour la remarque.

2019-02-25 20:32 UTC, amramo17 commented on dauphine-open-data-lib/src/main/java/io/github/oliviercailloux/y2018/opendata/entity/Lecture.java
>  	 */
Corrigé plutôt en conservant les commentaires sur les getters et setters.

2019-02-25 20:46 UTC, amramo17 commented on dauphine-open-data-lib/src/main/java/io/github/oliviercailloux/y2018/opendata/entity/Lecture.java
> +	private Date date;
Oui j'ai testé le code. Ci-dessous quelques traces.

![1](https://user-images.githubusercontent.com/33689217/53367573-6f535a80-393e-11e9-82b7-5bed47aa958f.png)

2019-02-26 13:54 UTC, oliviercailloux commented on dauphine-open-data-lib/src/main/java/io/github/oliviercailloux/y2018/opendata/entity/Lecture.java
> +	private Date date;
Je vous crois, pas besoin de preuve visuelle. Je voulais juste savoir si vous l’aviez bien testé.

2019-02-26 13:55 UTC, oliviercailloux approved these changes

2019-03-04 10:40 UTC, amramo17 commented
Bonjour Monsieur @oliviercailloux 
après votre confirmation des derniers changements, est ce que je peux mérger mes classes ?
En fait j'ai attendu votre feu vert sous forme de message ou commentaire dont vous m'autorisez le merge, car j'ai la crainte de tomber dans la mème erreur d avant.

2019-03-04 11:14 UTC, oliviercailloux commented
Oui oui, c’est approuvé.

2019-03-04 13:21 UTC, merged