Feat/vcard
edoreld/Dauphine-Data pull request #17
Opened 2019-03-22 00:11 UTC by omardjalo

Pour le compte de l'itération 2 : 
Voici l'implémentation de classe MapperVCard et une classe Test pour convertir l'entity Person au format Vcard.

2019-03-22 17:02 UTC, oliviercailloux requested changes

2019-03-22 17:02 UTC, oliviercailloux commented on pom.xml
> +			<version>0.10.3</version>
Pourquoi pas la dernière version ?

2019-03-22 17:02 UTC, oliviercailloux commented on dauphine-open-data-lib/src/test/java/io/github/oliviercailloux/y2018/opendata/MapperVcardTest.java
> +	}
Il serait plus pertinent d’enregistrer dans votre class path la vcard attendue et que le test compare la vcard enregistrée à la vcard attendue.

2019-03-22 17:02 UTC, oliviercailloux commented on dauphine-open-data-lib/src/main/java/io/github/oliviercailloux/y2018/opendata/mapper/MapperVcard.java
> +		vcard.setFormattedName(person.getFirstName() + " " + person.getLastName());
Je soupçonne que cette information redondante ne soit pas bienvenue (à moins que le standard l’exige, mais ça m’étonnerait).

2019-03-22 17:02 UTC, oliviercailloux commented on dauphine-open-data-lib/src/main/java/io/github/oliviercailloux/y2018/opendata/mapper/MapperVcard.java
> +		VCard vcard = new VCard();
Ne faut-il pas préciser qqpart qu’on utilise le format VCard 4 ? (Ou un autre, si un autre est retenu.)

2019-03-22 17:02 UTC, oliviercailloux commented on dauphine-open-data-lib/src/main/java/io/github/oliviercailloux/y2018/opendata/mapper/MapperVcard.java
> +			vcard.addRole(person.getOffice());
Je crois que ce n’est pas le rôle qui est fourni par `getOffice`, à vérifier et dites-moi si c’est bien le cas.

2019-03-22 17:02 UTC, oliviercailloux commented on dauphine-open-data-lib/src/main/java/io/github/oliviercailloux/y2018/opendata/mapper/MapperVcard.java
> +			vcard.addTelephoneNumber(person.getPhoneNumer());
Il serait sympathique de distinguer les types de n°. Ça ne sert pas à grand-chose d’avoir les deux n° de tél sans savoir lequel est un n° de fax.

2019-03-23 22:42 UTC, omardjalo commented on pom.xml
> +			<version>0.10.3</version>
Version récente ajouter

2019-03-23 22:45 UTC, omardjalo commented on dauphine-open-data-lib/src/main/java/io/github/oliviercailloux/y2018/opendata/mapper/MapperVcard.java
> +		VCard vcard = new VCard();
C'est mentionné, merci !

2019-03-23 22:52 UTC, omardjalo commented on dauphine-open-data-lib/src/main/java/io/github/oliviercailloux/y2018/opendata/mapper/MapperVcard.java
> +			vcard.addRole(person.getOffice());
Je ne trouvais rien de fourni pour getOffice et je m'étais dit qu'il y aurait une similarité avec le rôle... Néanmoins, j'ai utilisé note à la place qui peut contenir des formes libres de texte en espérant que ça puisse convenir

2019-03-23 22:52 UTC, omardjalo commented on dauphine-open-data-lib/src/main/java/io/github/oliviercailloux/y2018/opendata/mapper/MapperVcard.java
> +			vcard.addTelephoneNumber(person.getPhoneNumer());
Pris en compte, types rajoutés.

2019-03-23 22:53 UTC, omardjalo commented on dauphine-open-data-lib/src/main/java/io/github/oliviercailloux/y2018/opendata/mapper/MapperVcard.java
> +		vcard.setFormattedName(person.getFirstName() + " " + person.getLastName());
D'accord !

2019-03-24 18:23 UTC, oliviercailloux approved these changes
Ok pour fusion

2019-03-24 22:19 UTC, merged