Fonctionnalité client (2)
edoreld/Dauphine-Data pull request #23
Opened 2019-03-28 12:17 UTC by DBarthe

Bonjour Professeur,

Ceci est un cherry-pick de la PR #19 (Fonctionnalité client) vers la branche master, sans embarquer les commit de @ArnCLAUDEL. De cette façon cette PR est indépendante des autres et la revue peut se faire à temps.

Puisque le client swagger-ui est généré au runtime, il sera enrichi automatiquement au fur est à mesure que les autres PR seront mergées.

**Choix d'implementations**:
* Intégration de Swagger (OpenAPI) à notre API :
  * utilisation du connecteur swagger / jax-rs pour avoir une synchronisation automatique entre la description openapi et le code.
  * développement d'un [ReadListener Swagger custom](https://github.com/edoreld/Dauphine-Data/blob/feat/client-2/dauphine-open-data/src/main/java/io/github/oliviercailloux/y2018/opendata/resource/SwaggerOperationIdModifier.java) pour automatiser le nommage des routes avec une sémantique CRUD (listeObjects, createObject, replaceObject, deleteObject, getObject) 
* Client web swagger-ui déployé sur IbmCloud via le buildpack staticfile.
* Génération d'un client en ligne de commande grâce à openapi-generator
* ajout des headers CORS pour permettre l'utilisation de l'api par des clients tiers

2019-03-30 11:39 UTC, DBarthe commented
Bonjour @oliviercailloux , comme c'est le week-end je comprends que vous ayez mieux à faire que de corriger  nos pauvres lignes de Java.
Néanmoins, comme ça fait plus de 48h que la revue a été demandée, je me permets simplement de vous notifier.
Comme vous pourrez le lire dans la description, cette nouvelle PR est totalement indépendante de la PR de Arnaud.

2019-03-31 08:48 UTC, oliviercailloux requested changes
Vous faites bien de me relancer, j’avais raté la notification pour ce PR.

Ce travail me semble très utile et substantiel.

Pouvez-vous ajouter dans le README.adoc (ou dans un autre fichier, en ajoutant une référence vers ce fichier dans le README) une doc expliquant ce que vous avez fait pour des étudiants futurs (et pour moi !) ? Car ne connaissant pas Swagger, j’aurais des difficultés à les aiguiller. Il ne faut bien sûr pas expliquer tout vous même, des pointeurs adéquats suffisent vers des docs bien faites, et une introduction générale qui explique les fichiers et configurations importants dans ce projet.

Entretemps, la PR de Arnaud a été fusionnée, sauf erreur de ma part. Voyez SVP si jamais cela change qqch à la vôtre (j’imagine que non mais une petite vérification est peut-être utile).

2019-03-31 08:48 UTC, oliviercailloux commented on dauphine-open-data/src/main/webapp/openapi.yaml
> +- io.github.oliviercailloux.y2018.opendata.resource
Problème d’indentation.

2019-03-31 22:46 UTC, DBarthe commented on dauphine-open-data/src/main/webapp/openapi.yaml
> +- io.github.oliviercailloux.y2018.opendata.resource
Désolé je n'étais pas disponible dimanche.
Ceci n'est pas une erreur d'indentation, c'est souvent comme ça que le yaml est formaté par convention (par exemple https://kubernetes.io/docs/concepts/cluster-administration/manage-deployment/)

2019-03-31 22:48 UTC, DBarthe commented
Merci pour la revue. Je vais ajouter la doc demain.
Je n'ai pas eu la possibilité de travailler sur le projet ce dimanche. Merci de votre compréhension.

2019-04-01 12:22 UTC, DBarthe commented
@oliviercailloux :
* documentation swagger
* correction yaml
* rebase sur la branche master et regénération du CLI

2019-04-01 14:16 UTC, oliviercailloux approved these changes

2019-04-01 15:34 UTC, merged