Feat/refacto jaxrs test
edoreld/Dauphine-Data pull request #3
Opened 2019-01-10 17:28 UTC by ArnCLAUDEL

Bonjour,

Voici ma proposition pour la nouvelle base du projet.
Elle contient un socle de classes et interfaces pour faciliter la gestion des entités et de la base de données ainsi que l'implémentation d'une ressource JAX RS Restful, avec des tests arquillian.
Les entités viendront s'y greffer avec leur attributs et le code lié à la persistence.

2019-01-12 16:25 UTC, oliviercailloux requested changes
Vuillez vous ajouter comme Assigned, ce sera plus facile pour moi.

Je vous laisse corriger ce qui doit l’être, pour le reste ("pour info" ou les commentaires où j’ai indiqué que je n’étais pas à cheval sur une correction), vous choisissez si et comment vous corrigez. Vous pouvez ensuite fusionner sans me re-demander.

2019-01-12 16:25 UTC, oliviercailloux commented on pom.xml
> +		<version.jee.api>8.0</version.jee.api>
Je ne suis pas enitièrement convaincu par cette découpe entre les propriétés d’une part, dans laquelle les versions sont reprises, et leur utilisation de l’autre. Cela obscurcit plutôt que clarifie, à mon avis, car on ne voit plus le contexte de l’usage, on peut avoir des propriétés utilisées nulle part… En particulier quand les propriétés sont utilisées une seule fois, comme c’est le cas ici je pense. Et en particulier quand un commentaire mentionne, plus bas, Java EE 8, ce qui ne sera plus correct si on change la propriété mais pas le commentaire.

Mais il est vrai que c’est une découpe classique donc je ne m’y oppose pas.

2019-01-12 16:25 UTC, oliviercailloux commented on pom.xml
>  			<groupId>junit</groupId>
Veuillez utiliser Jupiter (JUnit 5) et non JUnit 4.

2019-01-12 16:25 UTC, oliviercailloux commented on dauphine-open-data-lib/pom.xml
> +	<parent>
Je suis légèrement dubitatif de l’intérêt des projets Maven multi-modules. Personnellement je m’en suis éloigné avec le temps. Ça apporte en fin de compte assez peu, et ça introduit des lourdeurs. 

D’une part, faire des choses compliquées avec les release, ça devient vite difficile à maintenir de toute façon, donc l’aide apportée par Maven est finalement assez faible. En outre, le mécanisme du parent POM peut être utilisé sans le mécanisme multi-module, à mon avis une recette gagnante.

D’autre part, il faut que tous les projets fils soient dans le même dépot GitHub (ou ça introduit encore plus de complexité), et tout contributeur est exposé à la complexité de la hiérarchie même s’il ne s’intéresse qu’à un sous-projet.

Mais c’est sans-doute subjectif, donc je ne m’y oppose pas.

2019-01-12 16:25 UTC, oliviercailloux commented on dauphine-open-data-lib/src/main/java/io/github/oliviercailloux/y2018/opendata/dao/AbstractDao.java
> +	public AbstractDao(final EntityManager entityManager, final Class<E> entityClass, final String entityName) {
Pour info, je ne mettrais pas systématiquement tous les arguments “final”. Ça encombre inutilement. Eclipse peut (et devrait) être configuré pour avertir si un argument est modifié, de toute façon. (Sur un champ ou dans une variable de méthode, bien sûr, c’est différent.)

2019-01-12 16:25 UTC, oliviercailloux commented on dauphine-open-data-lib/src/main/java/io/github/oliviercailloux/y2018/opendata/entity/AbstractEntity.java
> + * This mostly provides a nice flexibility for future features.
Pour info, j’en doute un peu. Au contraire, toutes vos entités doivent maintenant hériter de cette entité. Ça empêche d’hériter d’autre chose (éventuellement dans le futur du projet) si quelqu’un le souhaite. Ou bien, ça créera une architecture compliquée où une partie seulement des entités héritent de AbstractEntity. En outre, cette surcharge de equals et hashcode est peu visible pour qui ne regarde pas bien (ceci n’est pas un argument fort toutefois). Personnellement je favoriserais la composition sur l’héritage ici.

Mais vous pouvez aussi laisser comme ça et changer de stratégie si le besoin s’en fait sentir, ça ne me choque pas.

2019-01-12 16:25 UTC, oliviercailloux commented on dauphine-open-data-lib/src/main/java/io/github/oliviercailloux/y2018/opendata/entity/AbstractEntity.java
> +		return 0;
Il faut en tous cas changer cette implémentation de hashCode qui créera des problèmes de performance difficiles dont la source sera difficile à trouver !

2019-01-12 16:25 UTC, oliviercailloux commented on dauphine-open-data-lib/src/main/java/io/github/oliviercailloux/y2018/opendata/util/ExceptionalFunction.java
> + *
Envisager d’utiliser une bibliothèque adéquate, plutôt, telle que [Durian](https://github.com/diffplug/durian/blob/master/test/com/diffplug/common/base/ErrorsExample.java). Si pas applicable, commenter (au niveau du package utils) pourquoi elle ne l’est pas et pourquoi la solution manuelle a été privilégiée.

2019-01-12 16:25 UTC, oliviercailloux commented on dauphine-open-data/src/main/java/io/github/oliviercailloux/y2018/opendata/resource/AbstractResource.java
> + *
Ok en principe, cela peut être utile. Mais attention à la tentation de formatter votre API externe sur une base trop simple et sans sémantique particulière. L’utilisateur peut vouloir des opérations de granularité différente que simplement put / post etc. sur chaque ressource, et des noms de points d’accès plus parlants. À réfléchir au cas par cas.

2019-01-12 16:25 UTC, oliviercailloux commented on dauphine-open-data/src/main/java/io/github/oliviercailloux/y2018/opendata/resource/AbstractResource.java
> +	protected UserTransaction userTransaction;
Vous devriez idéalement vous en sortir en laissant le conteneur gérer les transactions, au moins là où c’est raisonnable. Cela simplifie le code conceptuellement. À voir en séance.

2019-01-12 16:25 UTC, oliviercailloux commented on dauphine-open-data/src/main/java/io/github/oliviercailloux/y2018/opendata/resource/AbstractResource.java
> +	public Response get(@PathParam("id") final String id) throws Exception {
JAX-RS vous permet de laisser le parsing des paramètres au conteneur. Vous pouvez recevoir directement l’id en long.

2019-01-12 16:25 UTC, oliviercailloux commented on dauphine-open-data/src/main/java/io/github/oliviercailloux/y2018/opendata/resource/AbstractResource.java
> +	public Response put(@PathParam("id") final String id, final E entity) throws Exception {
Sera difficile à utiliser par un utilisateur extérieur : ça lui apparaitra comme une contrainte redondante de devoir fournir une entité d’id identique à l’id déjà passé en paramètre. C’est un détail d’implémentation qui transparait ici dans l’API externe.

2019-01-12 16:25 UTC, oliviercailloux commented on dauphine-open-data/src/main/java/io/github/oliviercailloux/y2018/opendata/resource/AbstractResource.java
> +			return Response.noContent().build();
Idéalement : séparer traitement et réponse finale. Une seule réponse finale à la fin de la méthode. (Hormis les réponses d’erreur du début, avant le traitement.)
Donc : if (…) response = truc ; else response = machin.
return response.build();

Ou, si le dernier if est considéré aussi comme un cas d’erreur, il suffit d’enlever le else.

2019-01-12 16:37 UTC, oliviercailloux commented on dauphine-open-data-lib/src/main/java/io/github/oliviercailloux/y2018/opendata/dao/AbstractDao.java
> +	public AbstractDao(final EntityManager entityManager, final Class<E> entityClass, final String entityName) {
Il faut injecter l’entityManager, ça vous évite de le balader partout. C’est à ça que ça sert. On verra ça en séance prochaine.

2019-01-12 16:38 UTC, oliviercailloux commented on dauphine-open-data/src/main/java/io/github/oliviercailloux/y2018/opendata/DauphineOpenDataApp.java
> +	public Set<Class<?>> getClasses() {
Cela ne devrait pas être utile, normalement le conteneur trouve les ressources grâce aux annotations. Mieux vaut le laisser faire.

2019-01-12 16:39 UTC, oliviercailloux commented on dauphine-open-data/src/main/java/io/github/oliviercailloux/y2018/opendata/provider/ResponseHeaderProvider.java
> +		response.setLocale(DEFAULT_LOCALE);
Ce n’est pas ce que dit l’en-tête, default locale (french, par exemple). L’en-tête est correct, le code ne l’est pas.

2019-01-12 16:40 UTC, oliviercailloux commented on dauphine-open-data/src/main/java/io/github/oliviercailloux/y2018/opendata/resource/AbstractResource.java
> +	public void setDao(final D dao) {
field injection devrait fonctionner sans méthode set.

2019-01-12 16:48 UTC, ArnCLAUDEL commented on pom.xml
>  			<groupId>junit</groupId>
Arquillian fonctionne correctement avec Junit 5 ?
J'étais tombé sur des PoC assez récents proposant le support junit5 pour Arquillian et la plupart des exemples que j'ai vu utilisaient junit4.

Plus généralement, junit 5 est-il vraiment plus intéressant que junit 4 ? ou c'est simplement un pré-requis pour le projet ?

2019-01-12 16:59 UTC, ArnCLAUDEL commented on dauphine-open-data-lib/pom.xml
> +	<parent>
Ce choix reste subjectif effectivement et est clairement discutable pour ce projet.

Néanmoins je trouve le multi-module très intéressant, cela permet de bien distinguer les parties d'un projet et de ne pas avoir à rebuilder l'ensemble pour en modifier une partie. C'est assez pratique lorsque le temps de build est très long et que l'on souhaite juste compiler et tester unitairement notre module.
Le POM parent diminue les redondances dans la déclaration des dépendences et des propriétés et ça allège les poms des modules.  

Je reconnais que cela ajoute une certaine lourdeur mais, pour l'instant, je pense que ça en vaut le coup, rien que pour la séparation explicite du projet en sous module.

2019-01-12 17:04 UTC, ArnCLAUDEL commented on dauphine-open-data-lib/src/main/java/io/github/oliviercailloux/y2018/opendata/dao/AbstractDao.java
> +	public AbstractDao(final EntityManager entityManager, final Class<E> entityClass, final String entityName) {
Le bruit généré est effectivement assez important et je suis toujours partagé avec ce mot clé dans les arguments de méthode. Même si l'IDE génère un warning, je me dis souvent que ce n'est pas suffisant et je "troque" de la lisibilité contre l'assurance que mon argument ne sera jamais modifié dans ma méthode.

Mais je vois ça assez rarement dans les codes et je ne suis moi-même pas convaincu à 100% par cette pratique, je le retirerai surement dans la suite du projet.

2019-01-12 17:12 UTC, ArnCLAUDEL commented on dauphine-open-data-lib/src/main/java/io/github/oliviercailloux/y2018/opendata/entity/AbstractEntity.java
> + * This mostly provides a nice flexibility for future features.
Je comprends la problématique de l'héritage, en revanche je ne vois pas dans l'immédiat pourquoi une entité hériterait d'une autre classe. Etant donné qu'elles n'ont pour but que d'exposer leurs attributs, on peut imaginer suffisament de code commun pour certaines méthodes.
La composition fonctionnerait très bien mais je trouve l'héritage plus fort et, dans ce cas, je pense que les entités ne devraient pas s'éparpiller avec d'autres super classes.

2019-01-12 17:15 UTC, ArnCLAUDEL commented on dauphine-open-data/src/main/java/io/github/oliviercailloux/y2018/opendata/resource/AbstractResource.java
> + *
Effectivement pour l'instant nous n'avons qu'une API Rest qui ne fournit pas vraiment de service.
Lorsque nous aurons une vraie api, le format d'échange sera surement différent.
Je ne sais pas encore trop comment gérer les nouveaux services "non-rest", il faudra effectivement y réfléchir.

2019-01-12 17:16 UTC, ArnCLAUDEL commented on dauphine-open-data/src/main/java/io/github/oliviercailloux/y2018/opendata/resource/AbstractResource.java
> +	protected UserTransaction userTransaction;
A voir en séance effectivement car j'ai eu un peu de mal avec les transactions et je ne les comprends pas entièrement.

2019-01-12 17:18 UTC, ArnCLAUDEL commented on pom.xml
> +		<version.jee.api>8.0</version.jee.api>
Je ne suis moi même pas convaincu à 100% mais un point que j'apprécie est que l'on peut voir d'un coup toutes les versions des composants, sans avoir à scroller.

2019-01-12 17:19 UTC, ArnCLAUDEL commented on dauphine-open-data/src/main/java/io/github/oliviercailloux/y2018/opendata/resource/AbstractResource.java
> +	public Response get(@PathParam("id") final String id) throws Exception {
Très bien merci de l'info !

2019-01-12 17:31 UTC, ArnCLAUDEL commented on dauphine-open-data/src/main/java/io/github/oliviercailloux/y2018/opendata/resource/AbstractResource.java
> +			return Response.noContent().build();
Je comprends, je me suis déjà posé la question et il se trouve que je n'apprécie tant cette manière. Je préfère faire mes "returns" dès que possible car je pense que cela facilite la relecture de la méthode.

Je me suis retrouvé un certain nombre de fois à relire des méthodes assez lourdes, avec beaucoup de variables et de structures imbriquées, et j'étais donc obligé de lire le code entier pour comprendre où le traitement s'arrêtait vraiment et m'assurer qu'il n'y avait pas d'autres effets de bord.
En faisant un return dès que possible, on peut simplement ignorer le reste du code et être sûr qu'il ne se passera rien d'autres.

2019-01-12 17:34 UTC, ArnCLAUDEL commented on dauphine-open-data-lib/src/main/java/io/github/oliviercailloux/y2018/opendata/dao/AbstractDao.java
> +	public AbstractDao(final EntityManager entityManager, final Class<E> entityClass, final String entityName) {
L'entityManager est injecté via la DaoFactory qui elle expose les daos.
J'ai fait ce choix (discutable) d'externaliser l'injection car je ne pouvais pas utiliser l'injection par le constructeur (uniquement via les champs) et donc je ne pouvais pas le rendre "final".

2019-01-14 01:20 UTC, oliviercailloux commented on pom.xml
>  			<groupId>junit</groupId>
JUnit 5 contient quelques améliorations de l’API qui rendent le code plus élégant, entre autres en utilisant les lambdas (expl, pour tester les exceptions lancées). Mais c’est surtout une bonne politique par défaut de se baser sur des bibliothèques récentes.

Je n’avais pas pensé à Arquillian, je ne pense pas l’avoir essayé avec JUnit 5. C’est une bonne raison de rester au 4, dans ce cas. À documenter brièvement dans le POM.

2019-01-14 01:23 UTC, oliviercailloux commented on dauphine-open-data-lib/pom.xml
> +	<parent>
Concernant l’argument 1. C’est le cas aussi pour un projet non multi-module (en séparant simplement les parties dans des projets distincts).

Concernant l’argument 2. Comme l’indique mon commentaire, le POM parent est disponible même sans projet multi-module.

Mais comme j’écrivais, je ne suis pas à cheval sur ce point.

2019-01-14 01:29 UTC, oliviercailloux commented on pom.xml
> +		<version.jee.api>8.0</version.jee.api>
Pas vraiment (à cause des dépendances transitives). Pour ce faire il faut utiliser Maven dependency plug-in.

2019-01-14 01:39 UTC, oliviercailloux commented on dauphine-open-data/src/main/java/io/github/oliviercailloux/y2018/opendata/resource/AbstractResource.java
> +			return Response.noContent().build();
Comme j’écrivais en fin de commentaire (je m’en suis rendu compte après avoir écrit le reste), ici, nous sommes dans le cas d’un test d’erreur, et le return est parfaitement justifié, comme ceux des tests précédents. Par contre, il faut enlever le else.

En général, votre argument est valide dans le cas des tests d’erreur (http://wiki.c2.com/?GuardClause). Si vous voulez parler d’autres cas, je pense que vous faites erreur sur ce point. Je serais curieux d’avoir un exemple concret.

2019-01-14 01:40 UTC, oliviercailloux commented on dauphine-open-data-lib/src/main/java/io/github/oliviercailloux/y2018/opendata/dao/AbstractDao.java
> +	public AbstractDao(final EntityManager entityManager, final Class<E> entityClass, final String entityName) {
Vous pouvez utiliser l’injection via le constructeur. Cela devrait je pense être mentionné dans le tutoriel Java EE d’Oracle.

2019-02-04 09:44 UTC, merged

2019-02-11 16:20 UTC, DBarthe commented
@ArnCLAUDEL @oliviercailloux, le commit [`1b6143f`](/edoreld/Dauphine-Data/commit/1b6143fc6d6208477653684a96fc5e9e55649ef4) a été mergé prématurément via la PR #9, ce qui fait que github considère cette PR comme "succesfully merged and closed", même après avoir annulé la fusion. 

Je ne vois pas d'autres options que de recréer une nouvelle PR...

2019-02-22 11:35 UTC, ArnCLAUDEL commented
> Bonjour,
> 
> Je recréé une PR pour remplacer celle qui a été fermée par erreur.
> Vous trouverez donc les correctifs et la prise en compte des remarques.
> 
> Deux remarques sur cette PR:
> 
> * La classe AbstractEntity est désormais quasiment vide, elle sera supprimée à la prochaine itération. Les implémentations des méthodes equals, hashcode et toString seront faites dans les entités directement. Il n'y a donc plus vraiment de raison de la garder. Je la conserve pour l'instant pour ne pas casser le code existant utilisant cette classe.
> * La remarque concernant le header Locale dans ResponseHeaderProvider a peut être été mal comprise.
>   Je reposte le code et le commentaire ici:
> 
> `response.setLocale(DEFAULT_LOCALE);`
> 
> > Ce n’est pas ce que dit l’en-tête, default locale (french, par exemple). L’en-tête est correct, le code ne l’est pas.
> 
> Est-ce que vous faisiez référence à la méthode `Locale.getDefault()` ?
> Si c'est le cas, le nom de la constante peut être trompeur, il s'agit en fait du Locale par défaut de **l'application**.
> J'ai ajouté cela en commentaire de la constante.