filter on lecture
edoreld/Dauphine-Data pull request #34
Opened 2019-04-06 02:18 UTC by dostaric

Cette PR a été créée pour faciliter les requêtes sur la classe Lecture. Une route a été définie pour avoir accès à la fonctionnalité de recherche.
5 champs ont été considérés comme pertinents pour cette ces requêtes:
-le cours
-le nom du groupe d'étudiant qui suivent le cours
-la salle dans laquelle le cours se déroulera
_la personne qui donne le cours (son nom et son prénom)

2019-04-06 15:47 UTC, oliviercailloux commented
This branch has conflicts that must be resolved

2019-04-06 15:56 UTC, oliviercailloux requested changes

2019-04-06 15:56 UTC, oliviercailloux commented on dauphine-open-data-lib/src/main/java/io/github/oliviercailloux/y2018/opendata/dao/LectureDao.java
> +	protected EntityManager em;
Ne pas dupliquer ce champ.

2019-04-06 15:56 UTC, oliviercailloux commented on dauphine-open-data-lib/src/main/java/io/github/oliviercailloux/y2018/opendata/dao/LectureDao.java
> +        return lectures;
Formater code.

Quid des autres cas, non testés ? 

Modifier la logique pour utiliser une seule requête, paramétrée dynamiquement (utiliser Criteria API).

2019-04-06 18:49 UTC, dostaric commented on dauphine-open-data-lib/src/main/java/io/github/oliviercailloux/y2018/opendata/dao/LectureDao.java
> +        return lectures;
@oliviercailloux 
En effet j'ai commencé par travailler avec Javier sur les criteria Api. 
Ensuite J'ai voulu montrer qu'on pouvait faire autrement et ainsi enrichir notre travail. Cependant , il est vrai que pour une gestion dynamique, criteria Api est plus intéressant.
J'ai donc mis en place les criterias APi

2019-04-06 18:49 UTC, dostaric commented on dauphine-open-data-lib/src/main/java/io/github/oliviercailloux/y2018/opendata/dao/LectureDao.java
> +	protected EntityManager em;
Correction faite

2019-04-06 19:43 UTC, DBarthe commented on dauphine-open-data-lib/src/main/java/io/github/oliviercailloux/y2018/opendata/dao/PersonDao.java
> +@Dependent
@dostaric je ne sais pas ce que fait cette nouvelle annotation, est-ce que tu es sûr que ca ne va pas faire planter l'application ?

2019-04-06 20:24 UTC, dostaric commented on dauphine-open-data-lib/src/main/java/io/github/oliviercailloux/y2018/opendata/dao/PersonDao.java
> +@Dependent
@DBarthe  cela a été corrigé dans la pr filter on person et remplacer par RequestScoped. 
Là nous sommes dans la PR concernant les filtres pour la classe Lecture qui ne fait pas appel à la classe PersonDao.

2019-04-07 11:45 UTC, dostaric commented
@oliviercailloux 
La PR est prête pour la review

2019-04-07 17:30 UTC, oliviercailloux approved these changes

2019-04-07 17:35 UTC, oliviercailloux commented
Effectivement, l’annotation `@Dependent` n’est pas bienvenue (possible que le conteneur choisse le bon scope, mais je ne suis pas sûr que ce soit conforme aux specs car ce servlet Jax-rs n’est pas lui-même injecté dans un managed bean par vos soins) et je ne comprends pas votre réponse.

2019-04-07 19:49 UTC, dostaric commented
Bonsoir Monsieur,
En effet cette annotation @Dependent se trouvait dans la classe PersonDao , classe que j'ai mis à jour  en mettant l'annotation @RequestScoped. Cela a été modiifié dans la seconde  PR concernant les filtres sur la classe person. C'est ce que j'expliquais à Barth.

2019-04-07 19:50 UTC, merged