Feat/course
edoreld/Dauphine-Data pull request #5
Opened 2019-01-11 20:02 UTC by edoreld

This contains the implementation of the Course and CoursePart entities as well as the CourseDao file which has the operations to access the database. 

This request should be merged in sequential order after the https://github.com/edoreld/Dauphine-Open-Data/pull/3 pull request has been merged.

2019-01-14 00:40 UTC, oliviercailloux requested changes

2019-01-14 00:40 UTC, oliviercailloux commented on dauphine-open-data-lib/src/main/java/io/github/oliviercailloux/y2018/opendata/dao/CourseDao.java
> +	public Course persist(Course entity) throws EntityAlreadyExistsDaoException {
Ne fait pas ce que l’en-tête suggère : l’exception n’est jamais lancée. Test inutile car persist peut être appelé sur une entité déjà persistante, sauf erreur.

2019-01-14 00:40 UTC, oliviercailloux commented on dauphine-open-data-lib/src/main/java/io/github/oliviercailloux/y2018/opendata/dao/CourseDao.java
> +	public void remove(Long id) throws EntityDoesNotExistDaoException {
Même chose exception.

2019-01-14 00:40 UTC, oliviercailloux commented on dauphine-open-data-lib/src/main/java/io/github/oliviercailloux/y2018/opendata/entity/Course.java
> +		Preconditions.checkNotNull(courseName, "coursedescription");
Dans une autre classe vous autorisez les nulls et convertissez en "". Mettez-vous d’accord !

2019-01-14 00:40 UTC, oliviercailloux commented on dauphine-open-data-lib/src/main/java/io/github/oliviercailloux/y2018/opendata/entity/Course.java
> +	public int hashCode() {
Utiliser Objects.hashCode, code plus concis et erreurs moins faciles à commettre.

2019-01-14 00:40 UTC, oliviercailloux commented on dauphine-open-data-lib/src/main/java/io/github/oliviercailloux/y2018/opendata/entity/Course.java
> +		if (id == null) {
Que c’est compliqué ! Utiliser Objects.equals.

2019-01-14 00:40 UTC, oliviercailloux commented on dauphine-open-data-lib/src/main/java/io/github/oliviercailloux/y2018/opendata/entity/CoursePart.java
> +	public static long getSerialversionuid() {
Encombre l’API inutilement !

2019-01-14 00:40 UTC, oliviercailloux commented on dauphine-open-data-lib/src/main/java/io/github/oliviercailloux/y2018/opendata/entity/Course.java
> +	public Set<CoursePart> getCourseParts() {
Une EnumMap serait plus sympa. Permet entre autres de garantir que l’ensemble des parties ne contient pas plusieurs parties de même type, par exemple partie 1 TD 30 h, partie 2 TD 40 h. (Si l’intention est au contraire de l’autoriser, il faut le documenter, mais alors il faut j’imagine qqch qui distingue les parties !)

2019-01-14 00:40 UTC, oliviercailloux commented on dauphine-open-data-lib/src/main/java/io/github/oliviercailloux/y2018/opendata/entity/Course.java
> +		this.courseParts = courseParts;
Dangereux, il faut éviter modifications extérieures non voulues !

2019-02-07 17:54 UTC, edoreld commented
@oliviercailloux I've updated the code to conform to the review, could you check if it's okay to merge?

2019-02-10 13:26 UTC, oliviercailloux commented
Feat/lecture a été fusionné sans review préalable, sauf erreur de ma part. Veuillez d’abord annuler cette fusion.

2019-02-19 18:44 UTC, edoreld commented
@oliviercailloux fusion of feat/Lecture was cancelled, ok to merge this branch?

2019-02-19 20:57 UTC, oliviercailloux requested changes
A few minor things left.

2019-02-19 20:57 UTC, oliviercailloux commented on dauphine-open-data-lib/src/main/java/io/github/oliviercailloux/y2018/opendata/entity/Course.java
> +		return Objects.hashCode(this);
Ça, ça m’étonnerait que ça marche.

2019-02-19 20:57 UTC, oliviercailloux commented on dauphine-open-data-lib/src/main/java/io/github/oliviercailloux/y2018/opendata/entity/Course.java
> +		return Objects.equals(this, obj);
Même chose.

2019-02-19 20:57 UTC, oliviercailloux commented on dauphine-open-data/src/main/java/io/github/oliviercailloux/y2018/opendata/provider/ResponseHeaderProvider.java
> -	 * The application default locale. (Note that it is NOT the one returned by
Pedantic, but I’d write: “NOT necessarily”.

2019-02-20 13:58 UTC, edoreld commented
@oliviercailloux done. Good to go?

2019-02-21 08:40 UTC, oliviercailloux commented
C’est un peu dommage que vous ayez renoncé à utiliser `Objects.hashcode` comme j’avais demandé, plutôt que vous documenter sur son usage correct. Mais ce n’est pas un point bloquant. Ok pour la fusion.

2019-02-21 08:44 UTC, oliviercailloux approved these changes

2019-02-21 10:00 UTC, merged