Feat/planning
edoreld/Dauphine-Data pull request #8
Opened 2019-01-12 20:22 UTC by omardjalo

Bonjour Mr. @oliviercailloux,
 
Voici la PR de la classe Planning. Elle hérite de la PR #3 de @ArnCLAUDEL
Comme je fais référence à l'entité Lecture dans ma classe Planning, je l'ai crée  mais elle est vide.
Elle sera supprimée lors de la fusion car elle sera implémentée par un autre membre du groupe.

2019-01-15 17:11 UTC, oliviercailloux commented
Veuillez d’abord fusionner ce que j’ai déjà approuvé, pour réduire les changements apportés par le PR et qu’on voie qu’on avance.

2019-02-15 10:08 UTC, omardjalo commented
Bonjour Mr. @oliviercailloux, 

Afin de pouvoir apporter des améliorations possibles avant la date du 21/02, je souhaiterais SVP avoir un retour de votre part sur ma pull request.

Je vous remercie par avance.

2019-02-15 10:22 UTC, oliviercailloux commented
J’ai toujours l’impression que de nombreux changements déjà approuvés n’ont pas été fusionnés. GitHub m’indique 73 fichiers changés par votre PR, dont par exemple `AbstractDao`, dont l’auteur n’est pas vous. C’est pourquoi je vous demandais, le 15 janvier, d’effectuer la fusion d’abord.

2019-02-18 20:36 UTC, omardjalo commented
Oui en effet Mr @oliviercailloux, parce que ma PR hérite de celle de @ArnCLAUDEL comme indiqué dans le descriptif ci-haut. J'ai implémenté que les classes Planning et PlanningDao et pour le reste, c'est soit ça vient de PR de @ArnCLAUDEL ou c'est la classe lecture (vide) que j'ai crée parce que je l'appelle dans la mienne et qui est implémenté par un autre membre du groupe.

2019-02-19 12:16 UTC, oliviercailloux commented
Je vous prie de fusionner d’abord la PR de @ArnCLAUDEL . Vous ne me dites pas pourquoi cette solution ne vous convient pas.

2019-02-20 15:50 UTC, omardjalo commented
Mr. @oliviercailloux , la PR de @ArnCLAUDEL est fusionner

2019-02-21 08:46 UTC, oliviercailloux commented
Je vois 73 fichiers modifiés. Pouvez-vous faire en sorte que votre PR n’affiche que vos changements ?

2019-02-21 13:45 UTC, omardjalo commented
C'est fait Mr. @oliviercailloux, vous pouvez revérifier SVP !

2019-02-21 23:10 UTC, oliviercailloux commented
GitHub voit de multiples changements à des fichiers que vous ne semblez pas avoir changé (et déclarez n’avoir pas changé), par exemple Entity. Veuillez résoudre d’abord ce problème. Je soupçonne un problème de fins de lignes configuré différement (\r VS \r\n), ou de tabs, … Rouvrez ce PR ensuite.

2019-02-22 09:49 UTC, omardjalo commented
C'est réglé Mr. @oliviercailloux, vous pouviez regardé SVP

2019-02-24 10:47 UTC, omardjalo commented
Bonjour Mr. @oliviercailloux, je reste toujours en attente d'approbation de ma PR.

2019-02-24 16:16 UTC, oliviercailloux commented
Impossible de savoir si votre fct fonctionne sans la classe Lecture, qui est intimement liée au Planning. Merci de rouvrir ceci quand Lecture sera approuvée.

2019-02-24 17:25 UTC, omardjalo commented
@dostaric et @amramo17 pouviez vous SVP revoir vos PR (feat/person et feat feat/lecture) par rapport aux demandes de Mr. @oliviercailloux... Il faudrait que celles-ci soient approuvée pour que je puisse réouvrir la mienne

2019-02-24 23:09 UTC, oliviercailloux commented
Ce serait gentil de ne pas me @ mentionner quand je ne suis pas supposé être averti, sinon ça fait l’inverse de ce à quoi cette fonctionnalité est censée servir (c-à-d m’avertir quand je dois lire un message).

2019-03-05 09:26 UTC, omardjalo commented
Bonjour Mr. @oliviercailloux,
Est-ce que je peux à présent ré-ouvrir ma PR ? 
Merci par avance.

2019-03-05 11:59 UTC, oliviercailloux commented
Quand vous m’avez posé la quetion, la fct Person n’était pas encore approuvée, donc non.
Elle est maintenant approuvée.
Ouvrez votre PR lorsqu’elle est fusionnée SVP.

2019-03-05 13:16 UTC, omardjalo commented
Mr. @oliviercailloux,
Comme souhaité, les PR Lecture et Person sont approuvées et fusionnées, je vous demande à présent de regarder la mienne (Planning) SVP.
En vous remerciant par avance.

2019-03-05 17:28 UTC, oliviercailloux requested changes
Il est demandé de documenter vos choix. Comment envisagez-vous d’utiliser Planning ? Pourquoi est-ce une entité ? 

Dans mon esprit un planning correspond à tous les cours d’un enseignant sur une certaine période, et ne doit donc pas être une entité. Un choix différent est envisageable mais doit être réfléchi et documenté.

2019-03-05 17:28 UTC, oliviercailloux commented on dauphine-open-data-lib/src/main/java/io/github/oliviercailloux/y2018/opendata/entity/Planning.java
> +	public static long getSerialversionuid() {
Ceci ne sert à rien et obscurcit l’API.

2019-03-05 17:28 UTC, oliviercailloux commented on dauphine-open-data-lib/src/main/java/io/github/oliviercailloux/y2018/opendata/entity/Planning.java
> +	private Long id;
Type primitif pour éviter null

2019-03-05 17:28 UTC, oliviercailloux commented on dauphine-open-data-lib/src/main/java/io/github/oliviercailloux/y2018/opendata/entity/Planning.java
> +@XmlRootElement
Pourquoi ces annotations XML ? Avez-vous réellement l’intention de sérialiser en XML ?

2019-03-05 17:28 UTC, oliviercailloux commented on dauphine-open-data-lib/src/main/java/io/github/oliviercailloux/y2018/opendata/entity/Planning.java
> +	public void setLectures(List<Lecture> lectures) {
On ne doit pas pouvoir remplacer la liste, il faut utiliser la liste et la modifier.

2019-03-05 17:28 UTC, oliviercailloux commented on dauphine-open-data-lib/src/main/java/io/github/oliviercailloux/y2018/opendata/entity/Planning.java
> +	public void addLecture (final Lecture lecture) {
À mon avis, pas utile, car les modifications peuvent être effectuées via la liste elle-même, qui doit être utilisée de toute façon pour les autres modifications (telles que l’effacement).

2019-03-05 17:28 UTC, oliviercailloux commented on dauphine-open-data-lib/src/main/java/io/github/oliviercailloux/y2018/opendata/entity/Planning.java
> +	 * Returns this planning's lectures
Documenter que les changements dans la liste renvoyée sont reflétés dans cet objet.

2019-03-05 21:18 UTC, omardjalo commented on dauphine-open-data-lib/src/main/java/io/github/oliviercailloux/y2018/opendata/entity/Planning.java
> +	public void addLecture (final Lecture lecture) {
D'accord

2019-03-05 21:19 UTC, omardjalo commented on dauphine-open-data-lib/src/main/java/io/github/oliviercailloux/y2018/opendata/entity/Planning.java
> +	public void setLectures(List<Lecture> lectures) {
Ok, correction apportée

2019-03-05 21:35 UTC, omardjalo commented on dauphine-open-data-lib/src/main/java/io/github/oliviercailloux/y2018/opendata/entity/Planning.java
> +@XmlRootElement
Non pas forcement

2019-03-05 21:39 UTC, omardjalo commented
Mr. @oliviercailloux,
J'ai apporté les modifications, pouviez-vous regardé SVP !

2019-03-05 21:48 UTC, omardjalo commented on dauphine-open-data-lib/src/main/java/io/github/oliviercailloux/y2018/opendata/entity/Planning.java
> +	public static long getSerialversionuid() {
d'accord

2019-03-05 21:51 UTC, oliviercailloux approved these changes
Je reste à ce stade très sceptique concernant votre choix d’implémentation, avec une entité JPA qui me semble redondante et un objet peu utile. Mais le temps passe et il est largement temps de fusionner ceci et poursuivre. Nous en discuterons j’imagine en séance.

2019-03-05 21:57 UTC, merged